<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Humanizer" Version="2.14.1" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0"/>
        <PackageReference Include="OfficeOpenXml.Extension.AspNetCore" Version="1.0.0" />
        <PackageReference Include="Wkhtmltopdf.NetCore" Version="3.0.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\INV.App\INV.App.csproj" />
      <ProjectReference Include="..\INV.Domain\INV.Domain.csproj" />
      <ProjectReference Include="..\INV.Implementation\INV.Implementation.csproj" />
      <ProjectReference Include="..\INV.Infrastructure\INV.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="wkhtmltopdf\Windows\wkhtmltopdf.exe">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
