### Receipt_details
GET http://localhost:5095/receipt/DownloadPdf/C3C1E881-08CD-4EFC-8CB1-4C22EB14F343/Fr
###    
GET http://localhost:5095/receipt/DownloadPdf/937ADCF2-381B-4110-87A0-49B1C3DBDE7B/Ar



